"""Init_2

Revision ID: 77e3a87ae575
Revises: 331cf6ffd8ca
Create Date: 2023-08-02 17:25:01.043372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e3a87ae575'
down_revision = '331cf6ffd8ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
